#+TITLE Isolation Tank Gnosis

* Isolation in 13 Verses

In this chapter we lay down the complete doctrine of Isolation Tank
Gnosis in 13 verses. The rest of this text is simply elaborating
on what is tersely written here:

1. TRUTH exists for YOU Alone.
2. When others agree with YOU, it becomes a Reality
3. TRUTH is senior to Reality
3. TRUTH has the following synonyms GOD, Love, Oneness, Imagination,
   Delusion, Illusion, Sentience, Creativity, Life Force, and most
   significantly YOU.
3. Some have postulated that "GOD is All".
4. If so, then GOD is One
5. GOD as all one must be Alone.
6. In isolation, YOU are alone.
7. To these postulators, we can conclude: "In isolation YOU are GOD"
8. The Isolation Tank provides isolation.
9. I provide the isolation tank so that YOU may find TRUTH.
10. The absolutely capitalized words are: YOU, TRUTH, and GOD.
3. Because Time = Art in the Law of Time Calendar, it is the ideal
   timing system for prioritizing Imagination and Art over Science
   and Reason.

Now that the complete doctrine has been laid down, I would like to
acknowledge my source of inspriation for such a terse style of
delivery. It was completely inspired by Ramana Maharshi's text
"Reality in 40 Verses".


* TRUTH
** TRUTH IS 100% PERSONAL. YOU ARE NEVER SEPARATE FROM THE TRUTH
Truth is the most central topic in ITG because the purpose of ITG is
to aid the search for Truth. What is Truth? ITG adopts the definition
of truth laid down in "Spiritologie" by Andreas Buttler: "Truth exists for you
alone. If others agree with you, it becomes a Reality."

ITG considers illusion, delusion, imagination, dreams, fantasies and
hallucination to be synonomous with Truth.

Let us conclude this instruction on TRUTH with a quote from
"Spiritologie" by Andreas Buttler

#+begin_quote
Psychology is, so to speak, simply being ‘used’ and even only exists
 – with this phony theory of ‘normality’ – to give you a hellish fear
 of think- ing differently or being different from your environment.

I would like to invite you to please quit adjust- ing your personal
truth to that of the public and not even letting it be adjusted.
That is what truth really is, namely a personal, individual thing!
#+end_quote

* Reality
Reality occurs when *two* or more beings agree that something is
so. TRUTH occurs when *one being* says that something is so. Because
one proceeds two, TRUTH is primary and Reality secondary.

ITG exists to assist the return to TRUTH. Of course, since a being
can never leave the TRUTH, this is a ludicrous statement. But without
isolation, a being may not realize the ever-present TRUTH. So, we
provide the minimum amount of procedures and viewpoint to aid the
search.

We will conclude this chapter with two contrasting writings on Reality
and bit of commentary on each.

** "The world is in your mind" viewpoint
We need to define one term in the quote to follow and that is
"consideration". A consideration is a creative thought -- Michael
Jackson before composing "Billie Jean", Van Gogh before composing "A
Starry Night." So now let's read the quotation:

#+begin_quote
Considerations take rank over the mechanics of space, energy, and
time. By this it is meant that an idea or opinion is, fundamentally,
superior to space, energy, and time, or organizations of form, since
it is conceived that space, energy, and time are themselves broadly
agreed-upon considerations. That so many minds agree brings about
Reality in the form of space, energy, and time. These mechanics, then,
of space, energy, and time are the product of agreed- upon
considerations mutually held by life.

The aspects of existence when viewed from the level of Man, however,
is a reverse of the greater truth above for Man works on the secondary
opinion that mechanics are real, and that his own personal
considerations are less important than space, energy, and time. This
is an inversion. These mechanics of space, energy, and time, the
forms, objects and combinations thereof, have taken such precedence in
Man that they have become more important than considerations as such,
and so his ability is overpowered and he is unable to act freely in
the framework of mechanics. Man, therefore, has an inverted
view. Whereas considerations such as those he daily makes are the
actual source of space, energy, time and forms, Man is operating so as
not to alter his basic considerations; he therefore invalidates
himself by supposing another determinism of space, energy, time and
form. Although he is part of that which created these, he gives them
such strength and validity that his own considerations thereafter must
fall subordinate to space, energy, time, and form, and so he cannot
alter the Universe in which he dwells.

The freedom of an individual depends upon that individual’s freedom to
alter his considerations of space, energy, time, and forms of life and
his roles in it. If he cannot change his mind about these, he is then
fixed and enslaved amidst barriers such as those of the physical
universe, and barriers of his own creation. Man thus is seen to be
enslaved by barriers of his own creation. He creates these barriers
himself, or by agreeing with things which hold these barriers to be
actual.

There is a basic series of assumptions in processing, which
assumptions do not alter the philosophy of Scientology. The first of
these assumptions is that Man can have a greater freedom. The second
is that so long as he remains relatively sane, he desires a greater
freedom. And the third assumption is that the auditor desires to
deliver a greater freedom to that person with whom he is working. If
these assumptions are not agreed upon and are not used, then auditing
degenerates into “the observation of effect”, which is, of course, a
goal-less, soulless pursuit, and is, indeed, a pursuit which has
degraded what is called modern science.

The goal of processing is to bring an individual into such thorough
communication with the physical universe that he can regain the power
and ability of his own considerations (postulates).

-- L. Ron Hubbard "Scientology 0-8"
#+end_quote

Now, if considerations take rank over the mechanics of MEST (Matter,
Energy, Space and Time), then certainly creative thought processes
take rank over the entities and interactions within MEST as well!
This means that all of the hard and soft sciences are transient
fignments of imagination. It means that the late night news and every
recollection you agree occurred are as well. It means that any matter
perceived, animate or inanimate, is also collective imagination.

** "The world exists independant of your mind" viewpoint
We now will read a different


* Consiousness without an Object
** Planes of Being
*** Nothing
*** Consciousness (subject with no object)
*** Truth (subject with peronal objects and events)
*** Reality (subject with consensus objects and events)

* Reflection, summary and evaluation
Now that we've covered the various realms, let's summarize them:
| Level | Point of View                                | Description                                                                            | Signature Text                                  | Representative Systems                                                                           |
|     0 | None                                         | Utter nothingness                                                                      | "Hsin Hsin Ming" (The Book of Nothing) by Sosan | If anything, Zen Buddhism                                                                        |
|     1 | Subject with No Object                       | Pure being, Consciousness without an object, Advaita Vedana                            | "Reality in 40 Verses" by Ramana Maharshi       | Advaita Vedanta, Franklin Merrell-Wolff                                                          |
|     2 | Subject with Personal Objects                | TRUTH, Imagination, Illusion, Shamanic Journeying, Psychedelic Trips, Pure Mathematics | "Spiritologie"                                  | Isolation Tank Gnosis, Poetry, Dance, Art, Cartoons, Pure Mathematics, Quantum Physics           |
|     3 | Subject with Objects other Subjects Agree On | Reality                                                                                | Any classical mechanics textbook                | Applied mathematics, Science other than Quantum Physics, a Court of Law, Intentional Communities |
|       |                                              |                                                                                        |                                                 |                                                                                                  |

** COC p.217 is the admittance test. contrast with p.218
** Afow first page
* Isolation
Now, we begin to delve into the specifics of ITG's approach to
seeking Truth. As we have acknowledged before, many religious
organizations are in 100% agreement with our definition of
Truth. They simply have a different path to it.
** Isolation and God
** Isolation Tank, Described
*** e.r. interlocks are minimized to zero
*** p.91 - inner realities to be penetrated
*** p.129 "when given freedom from external..."

** tqc 71 - you can discover...
* Temple, Ceremony and Ritual
** COC p.38 = I prefer staying in my own center
** definition of terms
** Temple is designed to encourage social isolation
*** p.126 TDS
** The ceremony is done with a mind to reduce communication, control and coercion
*** p.210 - "Once you can get into the tank with no preprogramming..."
*** Ceremony outline
*** Big communication no-nos
**** no suggestions on what can or will be experienced
**** p.136 judgement of performance/accuracy
** Truth Ritual
** Greeting Ritual
** The ritual takes place
** Post-ritual should nurture social isolation
*** p. 129 "range of phenomena great than society will accept"
*** any post-communication is initiated by the
** Night time is an allright time
** Time limits

* Charge for Service
** Entirely free
** Donation based
** Pay full price
** Receive service on credit
** Patronize my business
* Alternative Isolation Techniques
We must remember that Isolation is a path to the Truth, not truth
itself. So, accurately, this chapter should be about ways to dwell in
Truth
** Yoga Nidra
** Plugging your ears
** Social Isolation
** Word Repetition
* From Reality to Truth over Time
** Dreamspell calendar - 13 moons + 1 day out of time
* From Reality to Truth
** via logical proof

** via God Out There chapter in simulations of god.

* Welcome
Welcome to Isolation Tank Gnosis (ITG), the religion where Isolation
is the The Way and Imagination the Path! Because Isolation Tank Gnosis
is simple, personal and experiential, there is very little
writing/instruction about it necessary.

** What it is
ITG is an organization whose sole purpose is to faciliate gnosis via
the isolation tank. Gnosis is knowing the Self via the self as
opposed to a church or a group.
** Why it is
ITG fills a necessary gap in the float space. Isolation is a viable research
topic and commercial venture. However neither of these is ideal for
in-depth spiritual exploration. A personal tank is best but perhaps
space and cost-prohibitive.
** How it came about
ITG came about over many iterations.
*** Columbus, OH floatation tank laws
*** [[http://www.thinkingallowed.com/2jlilly.html][Jeffrey Mishlove's inteview]] with Dr. Lilly
When I saw this interview, it was the match to the firecracker. This
is what drove me into action. At one point, Lilly says "That's the
Gnostic viewpoint. Transcendence via the Self as opposed to a church
or group."
*** The Spiritologie Teachings
I took a course in [[http://www.spiritologie.org/][Spiritologie]] and that acted as "cement" for
Dr. Lilly's comment on the Gnostic Viewpoint. The Spiritologie
teachings are firmly grounded in personal truth and imagination. The
free book is highly recommended.
*** Numerous Failings in Spiritual Groups
While The Way of the gnostic viewpoint was attractive, I found The
Path offered by various spiritual groups unworkable. It was only in
the tank that The Way and The Path could find harmonious marriage.
** What good is it
The value of ITG is it's staunch insistence on you having everything
you need to be free other than isolation of some sort. In short, we
reduce the number of external necessities to realization to one --- a
tank. In other religious organizations are number of things are
expected of you and can occur to you:
- Invalidation :: Have you ever been at a spiritual gathering and
                  said you felt a certain way, or understood
                  something in a certain way, and been laughed at or
                  told you were not correct? Well, I have many times
                  and I wanted a religion where that could not happen.
- Manipulation :: As I write this, a yoga teacher with over 50,000
                  students is being charged with rape of some of his
                  students. Whether he is guilty or not, we will
                  never know because we weren't there when it
                  happened. But what is certain is that surrendering
                  Your Way to someone else's Path makes you
                  susceptible to manipulation. ITG is designed to
                  eliminate this possibility as well as its close
                  friend, peer pressure.
- Deception :: p.40 CoC "I was doublecrossed"
- Dependency :: No longer is your path to freedom blocked by the
                rules, regulations or expections of a group. No longer
                do you need to bring flowers or queue up in a line
                for a few seconds with the enlightened master! A single
                ritual is available to you 24 hours a day, 7 days a
                week!
                #+begin_quote
                The Pied Pipe entrances and entrains the children.
                -- p. 38 COC
                #+end_quote

Now that we've gone over the basics of Isolation Tank Gnosis, we will
get agreement on a few topics so that we can you, and anyone else,
return to a realm of utter freedom and no need to agree with anyone!
** References, Acknowledgements and Further Reading
** Books by John Lilly
*** The Quiet Center
*** The Deep Self
*** Simulations of God
*** Center of the Cyclone
** [[http://www.thinkingallowed.com/2jlilly.html]["From Here to Alternity"]] - an interview with Dr. Lilly
** [[http://www.lawoftime.org/pdfs/Perpetual13MoonCalendar.pdf][Law of Time]]
***
