#+TITLE Isolation Tank Gnosis

* Truth
Truth is the most central topic in ITG because the purpose of ITG is
to aid the search for Truth. What is Truth? ITG adopts the definition
of truth laid down in "Spiritologie" by Andreas Buttler: "Truth exists for you
alone. If others agree with you, it becomes a Reality."

ITG considers illusion, delusion, imagination, dreams, fantasies and
hallucination to be synonomous with Truth.

Don't part with your illusions. When they are gone you may still
exist, but you will have ceased to lve.

** COC p.15 = time period 2
** COC p.38 = I prefer staying in my own center
** tqc 71 - you can discover...
** G. Spencer Brown Laws of Form (tqc 22) - simplest truth
** redact Lilly's "province of the mind" statement

** A Hailstorm of Truth
 psychology is, so to speak, simply being ‘used’ and even only exists
 – with this phony theory of ‘normality’ – to give you a hellish fear
 of think- ing differently or being different from your environment

I would like to invite you to please quit adjust- ing your personal truth to that of the public and not even letting it be adjusted. That is what truth really is, namely a personal, individual thing!
* Reality
Each of these is senior to,
and responsible for the existence of Reality in it's various guises - science,
mathematics, language, history, the late night news and any other spacetime
matrix which requires agreement between two or more beings.

** p.163 (tds? simulations?) - sane and pragmatic vs psychic, insane, nonsane
** p.191 (actual document simulations) - reality is =
** Not even the sharex experiences of JCL/Ichazo can turn reality into truth
*** p.145: Lilly encounters same spaces as Ichazo
** p.168 COC - table 5<
* Consiousness without an Object
** Planes of Being
*** Nothing
*** Consciousness (subject with no object)
*** Truth (subject with peronal objects and events)
*** Reality (subject with consensus objects and events)

* Reflection, summary and evaluation
Now that we've covered the various realms, let's summarize them:
| Level | Description         | Representative Systems                                                      |
|     0 | Utter nothingness   | What word of system could capture this?                                     |
|     1 | Pure Being          | Consciousness without an object, Advaita Vedana                             |
|     2 | Imagination / TRUTH | Isolation Tank Gnosis, Poetry, Cartoons, Pure Mathematics, Quantum Physics  |
|     3 | REALITY             | Science other than Quantum Physics, a Court of Law, Intentional Communities |
|       |                     |                                                                             |
** COC p.217 is the admittance test. contrast with p.218
** Afow first page
* Isolation
** Isolation and God
** Isolation Tank, Described
*** e.r. interlocks are minimized to zero
*** p.91 - inner realities to be penetrated
*** p.129 "when given freedom from external..."

* Temple, Ceremony and Ritual
** definition of terms
** Temple is designed to encourage social isolation
*** p.126 TDS
** The ceremony is done with a mind to reduce communication, control and coercion
*** p.210 - "Once you can get into the tank with no preprogramming..."
*** Ceremony outline
*** Big communication no-nos
**** no suggestions on what can or will be experienced
**** p.136 judgement of performance/accuracy
** Truth Ritual
** Greeting Ritual
** The ritual takes place
** Post-ritual should nurture social isolation
*** p. 129 "range of phenomena great than society will accept"
*** any post-communication is initiated by the
** Night time is an allright time
** Time limits

* Alternative Isolation Techniques
We must remember that Isolation is a path to the Truth, not truth
itself. So, accurately, this chapter should be about ways to dwell in
Truth
** Yoga Nidra
** Plugging your ears
** Social Isolation
** Word Repetition
* From Reality to Truth over Time
** Dreamspell calendar - 13 moons + 1 day out of time
* From Reality to Truth
** via logical proof

** via God Out There chapter in simulations of god.
* Welcome
Welcome to Isolation Tank Gnosis (ITG), the religion where Isolation
is the The Way and Imagination the Path! Because Isolation Tank Gnosis
is simple, personal and experiential, there is very little
writing/instruction about it necessary.

** What it is
ITG is an organization whose sole purpose is to faciliate gnosis via
the isolation tank. Gnosis is knowing the Self via the self as
opposed to a church or a group.
** Why it is
ITG fills a necessary gap in the float space. Isolation is a viable research
topic and commercial venture. However neither of these is ideal for
in-depth spiritual exploration. A personal tank is best but perhaps
space and cost-prohibitive.
** How it came about
ITG came about over many iterations.
*** Columbus, OH floatation tank laws
*** [[http://www.thinkingallowed.com/2jlilly.html][Jeffrey Mishlove's inteview]] with Dr. Lilly
When I saw this interview, it was the match to the firecracker. This
is what drove me into action. At one point, Lilly says "That's the
Gnostic viewpoint. Transcendence via the Self as opposed to a church
or group."
*** The Spiritologie Teachings
I took a course in [[http://www.spiritologie.org/][Spiritologie]] and that acted as "cement" for
Dr. Lilly's comment on the Gnostic Viewpoint. The Spiritologie
teachings are firmly grounded in personal truth and imagination. The
free book is highly recommended.
*** Numerous Failings in Spiritual Groups
While The Way of the gnostic viewpoint was attractive, I found The
Path offered by various spiritual groups unworkable. It was only in
the tank that The Way and The Path could find harmonious marriage.
** What good is it
The value of ITG is it's staunch insistence on you having everything
you need to be free other than isolation of some sort. In short, we
reduce the number of external necessities to realization to one --- a
tank. In other religious organizations are number of things are
expected of you and can occur to you:
- Invalidation :: Have you ever been at a spiritual gathering and
                  said you felt a certain way, or understood
                  something in a certain way, and been laughed at or
                  told you were not correct? Well, I have many times
                  and I wanted a religion where that could not happen.
- Manipulation :: As I write this, a yoga teacher with over 50,000
                  students is being charged with rape of some of his
                  students. Whether he is guilty or not, we will
                  never know because we weren't there when it
                  happened. But what is certain is that surrendering
                  Your Way to someone else's Path makes you
                  susceptible to manipulation. ITG is designed to
                  eliminate this possibility as well as its close
                  friend, peer pressure.
- Deception :: p.40 CoC "I was doublecrossed"
- Dependency :: No longer is your path to freedom blocked by the
                rules, regulations or expections of a group. No longer
                do you need to bring flowers or queue up in a line
                for a few seconds with the enlightened master! A single
                ritual is available to you 24 hours a day, 7 days a
                week!
                #+begin_quote
                The Pied Pipe entrances and entrains the children.
                -- p. 38 COC
                #+end_quote

Now that we've gone over the basics of Isolation Tank Gnosis, we will
get agreement on a few topics so that we can you, and anyone else,
return to a realm of utter freedom and no need to agree with anyone!
** References, Acknowledgements and Further Reading
** Books by John Lilly
*** The Quiet Center
*** The Deep Self
*** Simulations of God
*** Center of the Cyclone
** [[http://www.thinkingallowed.com/2jlilly.html]["From Here to Alternity"]] - an interview with Dr. Lilly
** [[http://www.lawoftime.org/pdfs/Perpetual13MoonCalendar.pdf][Law of Time]]
***
