
#+TITLE Lilly in the Wilderness

* Course

** What is Lilly in the Wilderness?

*** Equational Description
Truth = Imagination = Isolation = God = Wilderness =
Me in the Isolation Tank = You in the Isolation Tank.

*** Revelation Through Dialogue
MISHLOVE: And you seem to be saying that it's up to each person to in
effect make the same bridge that you have, and to create their own
belief system, so that in creating that belief they can move into the
state that that belief leads them to, so that they can then discard it
again.

LILLY: That's the gnostic point of view -- self transcendence, not
transcendence through a church or a group.
*** A most unusual concoction

Truth is imaginary, personal, impermanent and immediate.
In search of Truth, from the Gnostic Viewpoint, we walk the path of
isolation, not via nature and her wilderness but by floatation.

**** Floating
**** Isolation
**** Gnostic Viewpoint
**** Spiritologie
***** Definition of truth and reality
***** Value of imagination
***** A vision of rehabilitation of spiritual beings
***** A sensible cosmic history

***** The three universes
** Truth is imaginary, personal, impermanent and immediate
** Reality is shared imagination bubbles
** What is there other than Truth or Reality?
** Sex, Drugs and Epsom Salt: Floating and Truth
sex and drugs work just fine withot religious trappings. But people
feel compelled to make religions around them.

Religion is about truth.

*** Floating and Truth
**** Tank Logs
**** Tanks for the Memories
**** Bertil Fanger
**** Aubrey Marcus


** Isolation and Truth

"Laws as such do not make people better," said Mulla Nasrudin to the King; "they must practice certain things, in order to become attuned to inner truth.
- See more at:
  http://www.spiritual-short-stories.com/spiritual-short-story-452-How+Nasrudin+Created+Truth.html#sthash.WYqKn3gj.dpuf

*** from senses
**** spiritual references
**** scientific research
*** from civilization
*** God as Isolation
** Gnostic Viewpoint and Truth
- Invalidation :: Have you ever been at a spiritual gathering and
                  said you felt a certain way, or understood
                  something in a certain way, and been laughed at or
                  told you were not correct? Well, I have many times
                  and I wanted a religion where that could not happen.
- Manipulation :: As I write this, a yoga teacher with over 50,000
                  students is being charged with rape of some of his
                  students. Whether he is guilty or not, we will
                  never know because we weren't there when it
                  happened. But what is certain is that surrendering
                  Your Way to someone else's Path makes you
                  susceptible to manipulation. ITG is designed to
                  eliminate this possibility as well as its close
                  friend, peer pressure.
- Deception :: p.40 CoC "I was doublecrossed"
- Dependency :: No longer is your path to freedom blocked by the
                rules, regulations or expections of a group. No longer
                do you need to bring flowers or queue up in a line
                for a few seconds with the enlightened master! A single
                ritual is available to you 24 hours a day, 7 days a
                week!
                #+begin_quote
                The Pied Pipe entrances and entrains the children.
                -- p. 38 COC
                #+end_quote


** Belief 1 - I am God in Isolation
** Belief 2 - The Gnostic Viewpoint

** Belief 3 - Spiritologie
truth, imagination, spiritual and cosmic anatomy, history
universes

** Belief 4 - Flaoting takes you to absolute zero, transcending yet creating any
belief set
** Temple, Ceremony and Ritual - Belief application
*** Let's talk about God
- instantaneously all powerful. Therefore whatever we do should
  likewise be instantaneously all powerful.
*** Let's talk about spiritual search
"You arent broken and you can't be fixed" - Christopher Tims
What we do is simply strip away layers of non-you to get to you. We
remove clothing, gravity, light and sound and you are still around.


** Spiritologie - The Three Universes

** Spiritologie - Value of Imagination

** Spiritologie - God Defined

** Wilderness Scriptures and Texts
*** "Spiritologie" by Andreas Buttler
*** "Center of the Cycle" by John Lilly
*** "A Feeling of Weirdness" by John Lilly

** A solo path

** History
This religion was founded the moment I saw this video and this
statement by John C. Lilly.

I had been floating and reading John Lilly's books off
and on for a decade prior to that. I was finishing up a course in
Spiritologie right around this same time.

I had also built my own floatation tank. Somehow, that single sentence
encapsulated everything that I was doing. I immediately came up with
the name Gnostic Isolation Temple and took out an IRS number.

Then I cooled off for about 2 years and theb only July 1 2013 in
Boston, MA began working on the documents again as I commuted to work.

On Jun 27, I began intimate relations with Amita Wilson. I told her
about my love of Isolation and she asked me what was so important
about it. I had to figure out a good answer. I then began to work on
the documents again.

For some reason, I began to wonder if I had chosen the right name for
the religion. I looked for synonyms for Isolation and the term
Wilderness struck me, so I renamed the religion "Lilly in the
Wilderness".

** Pricing Structure
** Why is this religion important today
*** Health Board Protection
*** Self Esteem
*** Others see it
Bertil Fanger
Flotation Tanks as the Modern Sanctuaries

Aubrey Marcus
Aubrey is the creator of the Warrior Poet blog and podcast, and the CEO of Onnit. He will be with us at the conference to talk about float tanks as a tool for inner exploration.

** Business and this religion
** Heresy, Hypocrisy, Conflict Resolution, Excommunication

*** Invalidating

*** Attempting to influence anothers Truth

*** Confusing Truth with Reality
*** Approaching someone as master rather than servant
*** Mixing floatation with massage
*** The Hypocrisy of Collective Solitude
if we are using the self to discover the Self, why do we need this
doctrine at all?
