
#+TITLE Lilly in the Wilderness

* Course

** What is Lilly in the Wilderness?

*** Equational Description
Truth = Imagination = Isolation = God = Wilderness =
Me in the Isolation Tank = You in the Isolation Tank.

*** Revelation Through Dialogue
MISHLOVE: And you seem to be saying that it's up to each person to in
effect make the same bridge that you have, and to create their own
belief system, so that in creating that belief they can move into the
state that that belief leads them to, so that they can then discard it
again.

LILLY: That's the gnostic point of view -- self transcendence, not
transcendence through a church or a group.

** Wilderness Scriptures and Texts
*** "Spiritologie" by Andreas Buttler
*** "Center of the Cycle" by John Lilly
*** "A Feeling of Weirdness" by John Lilly

** Union with God through Temple, Ceremony and Ritual
*** Let's talk about God
- instantaneously all powerful. Therefore whatever we do should
  likewise be instantaneously all powerful.
*** Let's talk about spiritual search
"You arent broken and you can't be fixed" - Christopher Tims
What we do is simply strip away layers of non-you to get to you. We
remove clothing, gravity, light and sound and you are still around.

** History
This religion was founded the moment I saw this video and this
statement by John C. Lilly.

Prior to that, I had floated before. Once a decade before. Then for
2-3 weeks. Then in Florida. Then in Boston, MA I started drafting
version 1 of the training course

** Collective Solitude
